### ISSUE TITLE
Collection FS

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern-app#3]
Pacote deprecated, bscar outros packages para gerência do S3.

**Comment by andredornas** [comment]
Vi que a galera ta usando esses:
https://github.com/Lepozepo/S3
https://github.com/CulturalMe/meteor-slingshot

Pelo que vi dos projetos, o primeiro foi atualizado recentemente, pode ser melhor ele

**Comment by andredornas** [comment]
https://github.com/VeliovGroup/Meteor-Files

**Comment by deleuterio** [comment]
@andredornas encontrei esse bug ao tentar usar o package do s3 junto ao ostrio:
~~~shell
W20170209-10:29:12.462(-2)? (STDERR) /home/doug/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170209-10:29:12.463(-2)? (STDERR) 				throw(ex);
W20170209-10:29:12.463(-2)? (STDERR) 				^
W20170209-10:29:12.464(-2)? (STDERR) 
W20170209-10:29:12.464(-2)? (STDERR) Error: Can't find npm module 's3'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170209-10:29:12.465(-2)? (STDERR)     at Object.<anonymous> (/home/doug/git/lern-app/.meteor/local/build/programs/server/boot.js:200:17)
W20170209-10:29:12.465(-2)? (STDERR)     at Object.profileWrapper [as require] (/home/doug/git/lern-app/.meteor/local/build/programs/server/profile.js:281:16)
W20170209-10:29:12.466(-2)? (STDERR)     at options.fallback (packages/modules-runtime.js:445:18)
W20170209-10:29:12.466(-2)? (STDERR)     at require (packages/modules-runtime.js:112:16)
W20170209-10:29:12.467(-2)? (STDERR)     at profileWrapper (/home/doug/git/lern-app/.meteor/local/build/programs/server/profile.js:281:16)
W20170209-10:29:12.467(-2)? (STDERR)     at meteorInstall.node_modules.meteor.lsunsi:se-files.collections.images.js (packages/lsunsi:se-files/collections/images.js:4:12)
W20170209-10:29:12.468(-2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170209-10:29:12.468(-2)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20170209-10:29:12.468(-2)? (STDERR)     at profileWrapper (/home/doug/git/lern-app/.meteor/local/build/programs/server/profile.js:281:16)
W20170209-10:29:12.469(-2)? (STDERR)     at /home/doug/git/lern-app/.meteor/local/build/programs/server/packages/lsunsi_se-files.js:147:1
~~~

Essa linha `Error: Can't find npm module 's3'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?`, será que por acaso esse s3 você não instalou global no npm?
